Impossible for me to open Dropbox in Mac OS X 10.6.8 <body> I'm working with 2 different Mac systems: 10.1 and 10.6.8. I've installed Dropbox since 1 year. When I was working with Mac number one, the Dropbox of my computer number 2 was updated. But this morning, it's suddenly impossible to open Dropbox on the Snow Leopard Mac. I have nothing changedâ€¦  This is the error window:  img src="https://i.stack.imgur.com/Z3bLu.jpg" alt="enter image description here"  When I click on the blue link I get the following:  precodebn.BUILD_KEY: Dropbox bn.VERSION: 16.4.29 bn.DROPBOXEXT_VERSION: failed bn.is_frozen: True pid: 833 ppid: 98 uid: 501 user_info: pwd.struct_passwd(pw_name='blandinejet', pw_passwd='********', pw_uid=501, pw_gid=20, pw_gecos='Blandine JET', pw_dir='/Users/blandinejet', pw_shell='/bin/bash') effective_user_info: pwd.struct_passwd(pw_name='blandinejet', pw_passwd='********', pw_uid=501, pw_gid=20, pw_gecos='Blandine JET', pw_dir='/Users/blandinejet', pw_shell='/bin/bash') euid: 501 gid: 20 egid: 20 group_info: grp.struct_group(gr_name='staff', gr_passwd='*', gr_gid=20, gr_mem=['root']) effective_group_info: grp.struct_group(gr_name='staff', gr_passwd='*', gr_gid=20, gr_mem=['root']) DYLD_LIBRARY_PATH: None cwd: u'/Applications/Dropbox.app/Contents/Resources'      real_path=u'/Applications/Dropbox.app/Contents/Resources'             mode=040755 uid=501 gid=20      parent mode=040755 uid=501 gid=20 HOME: u'/Users/blandinejet' appdata: u'/Users/blandinejet/.dropbox/instance1'          real_path=u'/Users/blandinejet/.dropbox/instance1'                 mode=040700 uid=501 gid=20          parent mode=040700 uid=501 gid=20 dropbox_path: u'/Users/blandinejet/Dropbox'               real_path=u'/Users/blandinejet/Dropbox'                         not found               parent    mode=040755 uid=501 gid=20 sys_executable: '/Applications/Dropbox.app/Contents/MacOS/python'                 real_path='/Applications/Dropbox.app/Contents/MacOS/python'                         mode=0100755    uid=501 gid=20                 parent  mode=040755 uid=501 gid=20 trace.__file__: '/Applications/Dropbox.app/Contents/Resources/lib/python2.7/site-packages.zip/dropbox/client/ui/common/boot_error.pyo'                 real_path='/Applications/Dropbox.app/Contents/Resources/lib/python2.7/site-packages.zip/dropbox/client/ui/common/boot_error.pyo'                         not found                 parent  not found tempdir: u'/var/folders/rb/rb1PniUpG4Wxd06qp+-BGE+++TI/-Tmp-'          real_path=u'/private/var/folders/rb/rb1PniUpG4Wxd06qp+-BGE+++TI/-Tmp-'                 mode=040700 uid=501 gid=20          parent mode=040755 uid=501 gid=20 Traceback (most recent call last):   File "dropbox/client/main.pyo", line 5536, in main_startup   File "dropbox/client/main.pyo", line 2261, in run   File "ui/common/uikit.pyo", line 539, in create_ui_kit   File "ui/cocoa/uikit.pyo", line 41, in &lt;module&gt;   File "dropbox/client/ui/cocoa/tray_popup/tray_controller.pyo", line 48, in &lt;module&gt;   File "dropbox/client/ui/cocoa/tray_popup/tray_popup.pyo", line 115, in &lt;module&gt;   File "dropbox/client/ui/server_views/v2/cocoa/__init__.pyo", line 8, in &lt;module&gt;   File "dropbox/client/ui/server_views/v2/cocoa/embeddable.pyo", line 57, in &lt;module&gt;   File "dropbox/client/ui/server_views/v2/cocoa/webview.pyo", line 22, in &lt;module&gt;   File "Tungsten/__init__.pyo", line 29, in &lt;module&gt;   File "objc/_lazyimport.pyo", line 76, in __init__   File "objc/_lazyimport.pyo", line 38, in _loadBundle ImportError: Bundle could not be loaded /code/pre  So I tried to reinstall the application following the advises on your website:  ol liStop Dropbox (If needed): Click the Dropbox icon in the menu bar at the top of your screen Click on the gear icon in the Notifications panel and select 'Quit Dropbox'/li liDownload the newest version: www.dropbox.com/install/li liOpen your Terminal app (Located at /Applications/Utilities/Terminal) Copy and paste the following lines into the Terminal, ONE AT A TIME, and press ENTER after each one. PLEASE make sure you copy and paste these commands (don't type them by hand), as getting them wrong could cause some harm. You'll be prompted for your computer's admin password (not your Dropbox password) after entering the first command. Keep in mind that the password field in the terminal will remain blank as you type your password. After you type it, just press ENTER./li licodesudo chown "$USER" "$HOME"/codebr codesudo chown -R "$USER" ~/Dropbox/codebr codesudo chmod -R u+rw ~/Dropbox/codebr codesudo mv ~/.dropbox ~/.Trash/dropbox.old/codebr codesudo mv ~/.dropbox-master ~/.Trash/dropbox-master.old/codebr codesudo chmod -N ~/codebr codesudo mv /Library/DropboxHelperTools ~/DropboxHelperTools.old/code  /li liOpen the .dmg file from step # 2 and double click the Dropbox icon to install Dropbox./li liRestart Dropbox from the Applications folder./li /ol  strongBut/strong it doesn't change anything: it's impossible for me to open the application. Anyone (a genius) has an idea to help me?  <answer265997> You haven't completely uninstalled Dropbox. There are also files under /private/var/dropbox* . Also, remove all Dropbox related files including preferences. The easiest way to find out about that is by using applications like Appcleaner or Easyfind.   <comment333566> Those commands seem to have nothing to do with the errors /Users/blandinejet/Dropbox not found and /Applications/Dropbox.app/Contents/Resources/lib/python2.7/site-packages.zip/dropbox/client/ui/common/boot_error.pyo'                         not found - DO these two exist?