Python virtualenv not working on MacOS Seirra <body> Creating a virtual environment fails on MacOSX Seirra  When running codevirtualenv test/code  precodeNew python executable in /Users/sri/test/bin/python2.7 Also creating executable in /Users/sri/test/bin/python Please make sure you remove any previous custom paths from your /Users/sri/.pydistutils.cfg file. Installing setuptools, pip, wheel...   Complete output from command /Users/sri/test/bin/python2.7 - setuptools pip wheel:   Collecting setuptools   Using cached setuptools-35.0.2-py2.py3-none-any.whl Collecting pip Collecting wheel Collecting six&gt;=1.6.0 (from setuptools)   Using cached six-1.10.0-py2.py3-none-any.whl Collecting packaging&gt;=16.8 (from setuptools)   Using cached packaging-16.8-py2.py3-none-any.whl Collecting appdirs&gt;=1.4.0 (from setuptools)   Using cached appdirs-1.4.3-py2.py3-none-any.whl Collecting pyparsing (from packaging&gt;=16.8-&gt;setuptools)   Using cached pyparsing-2.2.0-py2.py3-none-any.whl Installing collected packages: six, pyparsing, packaging, appdirs, setuptools, pip, wheel Exception: Traceback (most recent call last):   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/basecommand.py", line 215, in main     status = self.run(options, args)   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/commands/install.py", line 342, in run     prefix=options.prefix_path,   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_set.py", line 784, in install     **kwargs   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_install.py", line 851, in install     self.move_wheel_files(self.source_dir, root=root, prefix=prefix)   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_install.py", line 1064, in move_wheel_files     isolated=self.isolated,   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/wheel.py", line 345, in move_wheel_files     clobber(source, lib_dir, True)   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/wheel.py", line 323, in clobber     shutil.copyfile(srcfile, destfile)   File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile     with open(dst, 'wb') as fdst: IOError: [Errno 13] Permission denied: '/lib/python2.7/site-packages/six.py' ---------------------------------------- ...Installing setuptools, pip, wheel...done. Traceback (most recent call last):   File "/usr/local/bin/virtualenv", line 11, in &lt;module&gt;     sys.exit(main())   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 713, in main     symlink=options.symlink)   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 945, in create_environment     download=download,   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 901, in install_wheel     call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 797, in call_subprocess     % (cmd_desc, proc.returncode)) OSError: Command /Users/sri/test/bin/python2.7 - setuptools pip wheel failed with error code 2 /code/pre  When I run the same with sudo codesudo virtualenv venv/code New python executable in /Users/shan/test/bin/python2.7  precodeAlso creating executable in /Users/shan/test/bin/python Please make sure you remove any previous custom paths from your /Users/shan/.pydistutils.cfg file. Installing setuptools, pip, wheel...   Complete output from command /Users/shan/test/bin/python2.7 - setuptools pip wheel:   The directory '/Users/shan/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag. The directory '/Users/shan/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag. Collecting setuptools Collecting pip Collecting wheel Installing collected packages: setuptools, pip, wheel Exception: Traceback (most recent call last):   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/basecommand.py", line 215, in main     status = self.run(options, args)   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/commands/install.py", line 342, in run     prefix=options.prefix_path,   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_set.py", line 784, in install     **kwargs   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_install.py", line 851, in install     self.move_wheel_files(self.source_dir, root=root, prefix=prefix)   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_install.py", line 1064, in move_wheel_files     isolated=self.isolated,   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/wheel.py", line 478, in move_wheel_files     generated.extend(maker.make(spec))   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 372, in make     self._make_script(entry, filenames, options=options)   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 276, in _make_script     self._write_script(scriptnames, shebang, script, filenames, ext)   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 250, in _write_script     self._fileop.write_binary_file(outname, script_bytes)   File "/usr/local/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/distlib/util.py", line 407, in write_binary_file     with open(path, 'wb') as f: IOError: [Errno 1] Operation not permitted: '/bin/easy_install' ---------------------------------------- ...Installing setuptools, pip, wheel...done. Traceback (most recent call last):   File "/usr/local/bin/virtualenv", line 11, in &lt;module&gt;     sys.exit(main())   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 713, in main     symlink=options.symlink)   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 945, in create_environment     download=download,   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 901, in install_wheel     call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 797, in call_subprocess     % (cmd_desc, proc.returncode)) OSError: Command /Users/shan/test/bin/python2.7 - setuptools pip wheel failed with error code 2 /code/pre  <answer284149> I'm running Sierra and virtual environments appear to work fine. What python distribution are you using? How did you initiate your virtual environment? I used Anaconda to install python and then followed their directions for setting up and activating virtual environments.  