automator and python script utf-8 output <body> I wrote a python shell script and it fails in automator workflow :  precode# -*- coding: utf-8 -*-  import urllib, json, os, datetime import locale locale.setlocale(locale.LC_ALL, 'fr_FR')  url = "http://feeds.delicious.com/v2/json/lefakir/ws?count=8"  urllib.urlopen(url)  deliciousFeed = urllib.urlopen(url)  posts = json.load(deliciousFeed)  for post in posts:     print " * {0} : [{1}]({2})".format(post["n"], post["d"], post["u"]) /code/pre  The problem occurs on post["n"] and post["d"] which have utf-8 symbols.  Is it a common issue ?  <answer176102> I found myself :  precodeprint " * {0} : [{1}]({2})".format(post["n"].encode( "utf-8" ), post["d"].encode( "utf-8" ), post["u"].encode( "utf-8" )) /code/pre  It was an unicode/utf-8 problem :)  <comment207780> Please can you add details about the error message you see and how you are using this script with Automator. <comment207781> Yes, this is a common issue. UTF-8 and Python quite often don't play nice. <comment207787> Sorry @GrahamMiln it's in french : http://grab.by/FrIG, but you can copy/paste this code in automator i think. <comment207788> @JohnKeates do you mean with automator or in a more general way ? <comment207789> With Python in a more general way. Unicode support requires some additional work to play nice with python. I learned this the hard way while working with SaltStack. <comment207811> I think that automator can't handle the unicode type, let's continue