Uninstall virtualenv, Mac <body> When trying to run a command:  precodepip uninstall virtualenv /code/pre  it raises an error:  precodeException: Traceback (most recent call last):   File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 122, in main     status = self.run(options, args)   File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/commands/uninstall.py", line 59, in run     requirement_set.uninstall(auto_confirm=options.yes)   File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1035, in uninstall     req.uninstall(auto_confirm=auto_confirm)   File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 568, in uninstall     for path in pip.wheel.uninstallation_paths(dist):   File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/wheel.py", line 375, in unique     for item in fn(*args, **kw):   File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/wheel.py", line 393, in uninstallation_paths     r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))   File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 1369, in get_metadata_lines     return yield_lines(self.get_metadata(name))   File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 1361, in get_metadata     return self._get(self._fn(self.egg_info,name))   File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/_vendor/pkg_resources.py", line 1470, in _get     stream = open(path, 'rb') IOError: [Errno 2] No such file or directory: '/Library/Python/2.7/site-packages/virtualenv-1.11.6.dist-info/RECORD'  Storing debug log for failure in /var/folders/qn/_rqylh917b33tgzrfm1wy79h0000gn/T/tmpFtrtEX /code/pre  I have no clue how to fix it, it start to show when I was trying to uninstall packages. Does anyone know how to solve the issue?  <answer178837> I encountered the same problem. I solved it by creating an empty file called codeRECORD/code in the codevirtualenv/code directory.   On my machine, the command to run in Terminal was   precode touch /usr/local/lib/python2.7/site-packages/virtualenv-1.11.6.dist-info/RECORD /code/pre  That's it. After doing that, codepip install virtualenv --upgrade/code worked for me.  <comment208263> Did you tried `sudo pip uninstall virtualenv`? <comment208266> doesn't work the same error