Terminal appears to ignore autoproxyurl setting <body> I can't get easy_install to install anything as it complains it gets a connection refused.:  precode  Searching for BeautifulSoup Reading https://pypi.python.org/simple/BeautifulSoup/ Download error on https://pypi.python.org/simple/BeautifulSoup/: [Errno 61] Connection refused -- Some packages may not be found! Couldn't find index page for 'BeautifulSoup' (maybe misspelled?) Scanning index of all packages (this may take a while) Reading https://pypi.python.org/simple/ Download error on https://pypi.python.org/simple/: [Errno 61] Connection refused -- Some packages may not be found! No local packages or download links found for BeautifulSoup error: Could not find suitable distribution for Requirement.parse('BeautifulSoup') /code/pre  If I query the interface I am told the proxy is setup and working (which it definitely appears to be as I can browse, etc.)  precodenetworksetup -getautoproxyurl Wi-fi URL: http://webproxy.******.co.uk/wpad.dat Enabled: Yes /code/pre  Visiting https://pypi.python.org/simple/ manually in a browser also works.  It gets more confusing;  I tried setting the proxies manually instead:  precodedjsmiley2k:~$ echo $HTTP_PROXY webproxy.*******.co.uk:8080 tbowers@tims-mbp:~$ echo $HTTPS_PROXY webproxy.*******.co.uk:8080 /code/pre  Still no dice :/  hr  Edit:  More urls appear to be affected, unsure if this is some weird resolving error I just happened to have hit at the wrong time:  precodedjsmiley2k:~/bin$ echo $HTTP_PROXY webproxy.*******.co.uk:8080 djsmiley2k:~/bin$ echo $HTTPS_PROXY webproxy.*******.co.uk:8080  djsmiley2k:~/bin$ wget https://bootstrap.pypa.io/get-pip.py --2015-05-18 15:30:33--  https://bootstrap.pypa.io/get-pip.py Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 185.31.18.175 Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|185.31.18.175|:443... failed: Connection refused. djsmiley2k:~/bin$ wget http://bootstrap.pypa.io/get-pip.py --2015-05-18 15:31:49--  http://bootstrap.pypa.io/get-pip.py Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 185.31.18.175 Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|185.31.18.175|:80... failed: Connection refused. /code/pre  I've checked and I can access the script directly in a browser, trying to go to http forwards me to https automatically. 